### PR TITLE
Use [].concat instead of Array.concat

### PR DESCRIPTION
**Pull request by betaveros**
It appears that Array.concat('foo') gives an array with a String object
instead of a primitive string value, and this breaks things. (I have no
idea why Array.concat even worked at all in the first place; it
definitely fails in Chrome, for example. Only Array.prototype.concat
seems to exist.)

Fixes setting the defsearch option.

### CODE REVIEW

**Comment by wshanks** [comment]
Thanks, it is working well for me. I went ahead and merged all of the other clean looking pull requests open on the 5digits repo as well.

**Comment by betaveros** [comment]
Thank you for updating the add-on and maintaining a signed xpi!

**Comment by wshanks** [comment]
By the way, one of the developers merged a pull request on 5digits/dactyl today, so it would be good to open this pull request there as well, so they have the option of merging it.

**Comment by betaveros** [comment]
I had to cherry-pick to keep the PR sensible, since the original had two commits below it. I hope this doesn't mess up git history too badly.

**Comment by matreex** [comment]
Hi, I want to know that can dactyl run on firefox aurora v51.0? I had installed but Hint mode is not working, it's points: "resource://dactyl/messages.jsm: 71: TypeError: this.bundles is null", please, can fix it?

**Comment by wshanks** [comment]
@matreex Open an issue here: https://github.com/5digits/dactyl/issues and hopefully someone will fix it.

It is pretty hard to use Pentadactyl with Aurora because changes to Firefox often break it.

**Comment by matreex** [comment]
@willsALMANJ Yes, I know, but... me too, it's very very hard to fix it on Aurora, so, I'm coming here. well, thank you much for you.

**Comment by matreex** [comment]
@willsALMANJ BOOM!!! v7300 is very very perfect, sooooooo... sweet! It's the great. dactyl is working on nightly v52a and aurora v51a. Thank you so much!

**Pull request merged**
